name: iris-community
services:
    iris:
        image: containers.intersystems.com/intersystems/iris-community:2024.2
        container_name: iris-community
        ports:
            - 1972:1972
            - 52773:52773
