name: iris-community
volumes:
    iris-data:
        driver: local
services:
    iris:
        image: containers.intersystems.com/intersystems/iris-community:2024.2
        container_name: iris-community
        ports:
            - 1972:1972
            - 52773:52773
        volumes:
            - iris-data:/usr/irissys
